/**
 * Code generated by protoc-gen-twirp_js v5.0.0, DO NOT EDIT.
 * source: stats.proto
 */
// import our twirp js library dependency
var createClient = require("twirp");
// import our protobuf definitions
var pb = require("./stats_pb.js");
Object.assign(module.exports, pb);

/**
 * Creates a new StatsServiceClient
 */
module.exports.createStatsServiceClient = function(baseurl, extraHeaders, useJSON) {
    var rpc = createClient(baseurl, "stats.StatsService", "v5.0.0",  useJSON, extraHeaders === undefined ? {} : extraHeaders);
    return {
        push: function(data) { return rpc("Push", data, pb.PushResponse); }
    }
}

