workspace:
  base: /microservice

kind: pipeline
name: build

steps:
- name: codegen
  image: titpetric/microservice-build
  pull: always
  commands:
    - make rpc
    - make templates
    - make build-cli
    - make migrate

- name: build
  image: titpetric/microservice-build
  pull: always
  commands:
    - make tidy
    - wire ./...
    - make lint
    - make build

services:
- name: mysql-test
  pull: always
  image: percona/percona-server:8.0.17
  ports:
    - 3306
  environment:
    MYSQL_ROOT_PASSWORD: default
    MYSQL_USER: migrations
    MYSQL_PASSWORD: migrations
    MYSQL_DATABASE: migrations
