version: '3.4'

services:
  stats:
    image: ${IMAGE_PREFIX}stats
    restart: always
    environment:
      DB_DSN: "stats:stats@tcp(db:3306)/stats"
      ELASTIC_APM_SERVICE_NAME: "stats"
      ELASTIC_APM_SERVER_URL: "http://apm:8200"
    command: [
      "-migrate-db-dsn=stats:stats@tcp(db:3306)/stats",
      "-migrate"
    ]

  elk:
    image: sebp/elk:740
    restart: always
    ports:
      - "5601:5601"

  apm:
    build: docker/apm

  db:
    image: percona/percona-server:8.0.17
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_slovenian_ci",
      "--default-authentication-plugin=mysql_native_password",
      "--max_connections=1000"
    ]
    volumes:
    - ./docker/dev/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    restart: always
