package stats

// file is autogenerated, do not modify here, see
// generator and template: templates/client_client.go.tpl

import (
	"net/http"

	"github.com/titpetric/microservice/rpc/stats"
)

func New() stats.StatsService {
	return NewCustom("http://stats.service:3000", &http.Client{})
}

func NewCustom(addr string, client *http.Client) stats.StatsService {
	return stats.NewStatsServiceJSONClient(addr, client)
}
