package main

// file is autogenerated, do not modify here, see
// generator and template: templates/cmd_main.go.tpl

import (
	"flag"
	"log"

	"net/http"

	_ "github.com/go-sql-driver/mysql"
	"github.com/SentimensRG/sigctx"

	"${MODULE}/db"
	"${MODULE}/internal"
	"${MODULE}/rpc/${SERVICE}"
	server "${MODULE}/server/${SERVICE}"
)

func main() {
	var config struct {
		migrate bool
		migrateDB db.ConnectionOptions
	}
	flag.StringVar(&config.migrateDB.Credentials.Driver, "migrate-db-driver", "mysql", "Migrations: Database driver")
	flag.StringVar(&config.migrateDB.Credentials.DSN, "migrate-db-dsn", "", "Migrations: DSN for database connection")
	flag.BoolVar(&config.migrate, "migrate", false, "Run migrations?")
	flag.Parse()

	ctx := sigctx.New()

	if config.migrate {
		handle, err := db.ConnectWithRetry(ctx, config.migrateDB)
		if err != nil {
			log.Fatalf("Error connecting to database: %+v", err)
		}
		if err := db.Run("${SERVICE}", handle); err != nil {
			log.Fatalf("An error occured: %+v", err)
		}
	}

	srv, err := server.New(ctx)
	if err != nil {
		log.Fatalf("Error in service.New(): %+v", err)
	}

	twirpHandler := ${SERVICE}.New${SERVICE_CAMEL}ServiceServer(srv, nil)

	log.Println("Starting service on port :3000")
	http.ListenAndServe(":3000", internal.WrapWithIP(twirpHandler))
}
